# Numpy
- Numpy - Numerical Python
- Numerical Operation / Computing
    ### Application
    - 1.Linear Algebra
    - 2.Statistics
    - 3.Probability
    - 4.Trignometric Operations(sin,cos,tan,etc....)
    - 5.Matrix
    - 6.Image Processing
    - 7.Logarithmic

## Array
- It is a collection of homogeneous Dataypes
- ndarray --> n-dimensional array
- Arrays are Faster than list
- Arrays are stored in conitgious manner
- Numpy is written in C/C++ language(Partially in Python)
- Arrays can be created with the help of tuples and list
- Supported Datatypes = int,float,comple,str

In [2]:
li = [1,1.5,"2"]
li

[1, 1.5, '2']

# Creating Numpy Arrays

In [3]:
import numpy as np

In [5]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [6]:
array = np.array([1,2,3,4.4,5.5])
array

array([1. , 2. , 3. , 4.4, 5.5])

In [7]:
array = np.array([1,2.2,3,4.4,5.5])
array

array([1. , 2.2, 3. , 4.4, 5.5])

In [8]:
array = np.array([1,2.2,3,4,5,"Python"])
array

array(['1', '2.2', '3', '4', '5', 'Python'], dtype='<U32')

In [9]:
array = np.array([1,2.2,3,4,5,5+3j])
array

array([1. +0.j, 2.2+0.j, 3. +0.j, 4. +0.j, 5. +0.j, 5. +3.j])

In [10]:
array = np.array([1,2.2,3,5+3j,4,5])
array

array([1. +0.j, 2.2+0.j, 3. +0.j, 5. +3.j, 4. +0.j, 5. +0.j])

In [11]:
array = np.array([1,2.2,3,5+3j,4,5,"P"])
array

array(['1', '2.2', '3', '(5+3j)', '4', '5', 'P'], dtype='<U64')

In [12]:
array = np.array([1.5,2.2,3.5,4,5.5])
array

array([1.5, 2.2, 3.5, 4. , 5.5])

# Change Data type of an Array

In [4]:
li = [1,2,3,4,5]
for i in li:
    print(float(i)) 

1.0
2.0
3.0
4.0
5.0


In [14]:
float(1)

1.0

In [15]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5])
array

array([1. , 2. , 3. , 4. , 5. , 6.5, 7.5, 8.5])

In [16]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=int)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=float)
array

array([1. , 2. , 3. , 4. , 5. , 6.5, 7.5, 8.5])

In [18]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=complex)
array

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5. +0.j, 6.5+0.j, 7.5+0.j,
       8.5+0.j])

In [19]:
np.array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5. +0.j, 6.5+0.j, 7.5+0.j,
       8.5+0.j],dtype=int)

TypeError: can't convert complex to int

In [20]:
int(5+5j)

TypeError: can't convert complex to int

In [21]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=int)
array / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [22]:
li = [1,2,3]
li / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [23]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=int)
array // 2

array([0, 1, 1, 2, 2, 3, 3, 4], dtype=int32)

In [25]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=int)
array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)