# Numpy

## Dimensions in Array

### 1. 0-D Array

In [1]:
import numpy as np

In [2]:
arr = np.array(1000)
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> 1000
Number of dimensions = 0


In [3]:
arr = np.array("Array 1")
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> Array 1
Number of dimensions = 0


In [4]:
arr = np.array("1",int)
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> 1
Number of dimensions = 0


In [5]:
arr = np.array(100.5,int)
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> 100
Number of dimensions = 0


### 2. 1-D Array
- It is a collection of 0-dimensional arrays

In [6]:
arr = np.array([100.5,200,300,400,500],int)
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> [100 200 300 400 500]
Number of dimensions = 1


In [7]:
arr = np.array([100],int)
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> [100]
Number of dimensions = 1


In [8]:
arr = np.array(100,int)
print(f"Array --> {arr}")
print(f"Number of dimensions = {arr.ndim}")

Array --> 100
Number of dimensions = 0


### 3. 2-D Array
- It is a collection of 1-dimemsional arrays

In [11]:
arr = np.array([[100.5,200,300,400,500],[100.5,200,300,400,500],[100.5,200,300,400,500]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[100 200 300 400 500]
 [100 200 300 400 500]
 [100 200 300 400 500]]
Number of dimensions = 2
Length --> 3
Shape of an array --> (3, 5)


In [12]:
arr = np.array([[100,200,300],[100,200,300],[100,200,300]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[100 200 300]
 [100 200 300]
 [100 200 300]]
Number of dimensions = 2
Length --> 3
Shape of an array --> (3, 3)


In [13]:
arr = np.array([[100,200,300],[100,200,300],[100,200,300,400]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [14]:
arr = np.array([[200,300,1,2,3],[200,300,4,5,6]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[200 300   1   2   3]
 [200 300   4   5   6]]
Number of dimensions = 2
Length --> 2
Shape of an array --> (2, 5)


In [15]:
arr = np.array([[200,300,1,2,3]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[200 300   1   2   3]]
Number of dimensions = 2
Length --> 1
Shape of an array --> (1, 5)


### 4. 3 - D Array
- It is a collection of 2-dimensional arrays

In [18]:
arr = np.array([[[200,300,1,2,3],[200,300,4,5,6]],[[200,300,1,2,3],[200,300,4,5,6]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[200 300   1   2   3]
  [200 300   4   5   6]]

 [[200 300   1   2   3]
  [200 300   4   5   6]]]
Number of dimensions = 3
Length --> 2
Shape of an array --> (2, 2, 5)


In [19]:
arr = np.array([[[200,300,1,2,3],[200,300,4,5,6]],[[200,300,1,2,3],[200,300,4,5,6]],[[200,300,1,2,3],[200,300,4,5,6]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[200 300   1   2   3]
  [200 300   4   5   6]]

 [[200 300   1   2   3]
  [200 300   4   5   6]]

 [[200 300   1   2   3]
  [200 300   4   5   6]]]
Number of dimensions = 3
Length --> 3
Shape of an array --> (3, 2, 5)


In [21]:
arr = np.array([[[200,300],[200,300]],[[200,300],[200,300]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[200 300]
  [200 300]]

 [[200 300]
  [200 300]]]
Number of dimensions = 3
Length --> 2
Shape of an array --> (2, 2, 2)


In [24]:
arr = np.array([[[200]],[[200]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[200]]

 [[200]]]
Number of dimensions = 3
Length --> 2
Shape of an array --> (2, 1, 1)


In [26]:
arr = np.array([[[1]],[[1]],[[1]],[[1]],[[1]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]]
Number of dimensions = 3
Length --> 5
Shape of an array --> (5, 1, 1)


In [27]:
arr = np.array([[[1,2]],[[1,2]],[[1,2]],[[1,2]],[[1,2]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[1 2]]

 [[1 2]]

 [[1 2]]

 [[1 2]]

 [[1 2]]]
Number of dimensions = 3
Length --> 5
Shape of an array --> (5, 1, 2)


## Indexing and Slicing

In [28]:
li = [1,2,3,4,5]
li[1]

2

In [29]:
li[4]

5

In [30]:
li[-2]

4

In [31]:
li[2:4]

[3, 4]

In [32]:
arr = np.array([100,200,300,400,500,600,700,800,900,1000])
arr

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [33]:
arr[0]

100

In [34]:
arr[1]

200

In [35]:
arr[-1]

1000

In [36]:
arr[-2]

900

In [37]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [38]:
arr[0:5]

array([100, 200, 300, 400, 500])

In [39]:
arr[0:]

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [40]:
arr[5:]

array([ 600,  700,  800,  900, 1000])

In [41]:
arr[:8]

array([100, 200, 300, 400, 500, 600, 700, 800])

In [42]:
arr[::-1]

array([1000,  900,  800,  700,  600,  500,  400,  300,  200,  100])

In [43]:
arr

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [44]:
arr[-5:-2]

array([600, 700, 800])

In [46]:
arr[-2:-5:-1]

array([900, 800, 700])

In [47]:
[[1,2],[3,4]][0]

[1, 2]

In [48]:
[[1,2],[3,4]][0][-1]

2

In [49]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
Number of dimensions = 2
Length --> 3
Shape of an array --> (3, 5)


In [50]:
arr[0]

array([1, 2, 3, 4, 5])

In [52]:
arr[0][-2:]

array([4, 5])

In [54]:
arr[1][1:4]

array([20, 30, 40])

In [55]:
arr

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [56]:
arr[0:2,0:2]

array([[ 1,  2],
       [10, 20]])

In [65]:
arr[0:3,0:4] 

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [70]:
arr[1:,3:]

array([[ 40,  50],
       [400, 500]])

In [71]:
arr[1:,2:]

array([[ 30,  40,  50],
       [300, 400, 500]])

In [80]:
arr = np.array([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]],[[11,22,33,44,55],[110,220,330,440,550],[1100,2200,3300,4400,5500]]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[   1    2    3    4    5]
  [  10   20   30   40   50]
  [ 100  200  300  400  500]]

 [[  11   22   33   44   55]
  [ 110  220  330  440  550]
  [1100 2200 3300 4400 5500]]]
Number of dimensions = 3
Length --> 2
Shape of an array --> (2, 3, 5)


In [81]:
arr[0]

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [82]:
arr[1]

array([[  11,   22,   33,   44,   55],
       [ 110,  220,  330,  440,  550],
       [1100, 2200, 3300, 4400, 5500]])

In [83]:
arr[0,0,0]

1

In [84]:
arr[0,0,-1]

5

In [85]:
arr[1,0,-1]

55

In [86]:
arr[0,2,-1]

500

In [87]:
arr[0,:,2:4]

array([[  3,   4],
       [ 30,  40],
       [300, 400]])

In [88]:
arr

array([[[   1,    2,    3,    4,    5],
        [  10,   20,   30,   40,   50],
        [ 100,  200,  300,  400,  500]],

       [[  11,   22,   33,   44,   55],
        [ 110,  220,  330,  440,  550],
        [1100, 2200, 3300, 4400, 5500]]])

In [91]:
arr[1,1:,2]

array([ 330, 3300])

In [92]:
arr[1,1:,2:4]

array([[ 330,  440],
       [3300, 4400]])

In [93]:
arr[:,1:,2:4]

array([[[  30,   40],
        [ 300,  400]],

       [[ 330,  440],
        [3300, 4400]]])

In [98]:
arr[:,:,:]

array([[[   1,    2,    3,    4,    5],
        [  10,   20,   30,   40,   50],
        [ 100,  200,  300,  400,  500]],

       [[  11,   22,   33,   44,   55],
        [ 110,  220,  330,  440,  550],
        [1100, 2200, 3300, 4400, 5500]]])

In [95]:
arr[:,:,2]

array([[   3,   30,  300],
       [  33,  330, 3300]])

In [97]:
arr[:,:,-2]

array([[   4,   40,  400],
       [  44,  440, 4400]])

In [99]:
arr[:,:,1:3]

array([[[   2,    3],
        [  20,   30],
        [ 200,  300]],

       [[  22,   33],
        [ 220,  330],
        [2200, 3300]]])

# Covert to n-D Array

In [100]:
arr = np.array([1,2,3,4,5],int)
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[1 2 3 4 5]
Number of Dimensions = 1
Length --> 5
Shape of an array --> (5,)


In [101]:
arr = np.array([1,2,3,4,5],ndmin=1)
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[1 2 3 4 5]
Number of Dimensions = 1
Length --> 5
Shape of an array --> (5,)


In [102]:
arr = np.array([1,2,3,4,5],ndmin=2)
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[1 2 3 4 5]]
Number of Dimensions = 2
Length --> 1
Shape of an array --> (1, 5)


In [103]:
arr = np.array([1,2,3,4,5],ndmin=3)
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[1 2 3 4 5]]]
Number of Dimensions = 3
Length --> 1
Shape of an array --> (1, 1, 5)


In [108]:
arr = np.array([1,2,3,4,5],ndmin=32)  # -----> max Dimensions = 32
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
Number of Dimensions = 32
Length --> 1
Shape of an array --> (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5)


In [110]:
arr = np.array([1,2,3,4,5],ndmin=0) # Cant convert 1-d to 0-d
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[1 2 3 4 5]
Number of Dimensions = 1
Length --> 5
Shape of an array --> (5,)


In [111]:
arr = np.array([1,2,3,4,5])
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[1 2 3 4 5]
Number of Dimensions = 1
Length --> 5
Shape of an array --> (5,)


In [115]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[1 2 3]
 [4 5 6]]
Number of Dimensions = 2
Length --> 2
Shape of an array --> (2, 3)


In [116]:
arr = np.array([[1,2,3],[4,5,6]],ndmin=1)
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[1 2 3]
 [4 5 6]]
Number of Dimensions = 2
Length --> 2
Shape of an array --> (2, 3)


In [117]:
arr = np.array([[1,2,3],[4,5,6]],ndmin=3)
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[[1 2 3]
  [4 5 6]]]
Number of Dimensions = 3
Length --> 1
Shape of an array --> (1, 2, 3)


In [118]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [120]:
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=3)
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [121]:
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=4)
arr

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]])

# reshape()
- reshape size must be multiple of elements in array

In [122]:
arr = np.array([1,2,3,4,5,6])
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[1 2 3 4 5 6]
Number of Dimensions = 1
Length --> 6
Shape of an array --> (6,)


In [123]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
arr

array([1, 2, 3, 4, 5, 6])

In [129]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [130]:
arr = np.array([[1,2,3],[4,5,1],[2,3,4],[5,1,2]])
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]
Number of Dimensions = 2
Length --> 4
Shape of an array --> (4, 3)


In [131]:
arr.reshape(6,2)  

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5],
       [1, 2]])

In [132]:
arr.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2]])

In [133]:
arr.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2]])

In [134]:
arr.reshape(12,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2]])

In [135]:
arr.reshape(2,6)  # 2*6 --> 12

array([[1, 2, 3, 4, 5, 1],
       [2, 3, 4, 5, 1, 2]])

In [136]:
arr.reshape(3,6)  # 3*6 --> 18 != 12

ValueError: cannot reshape array of size 12 into shape (3,6)

# 1-D to 3-D Coversion

In [137]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Number of Dimensions = 1
Length --> 12
Shape of an array --> (12,)


In [138]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [139]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [140]:
arr.reshape(6,2,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]],

       [[11],
        [12]]])

In [141]:
arr.reshape(1,2,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [142]:
arr.reshape(1,12,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [143]:
arr.reshape(1,1,12)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

# Accesing elements by for loop

In [144]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"Array --> \n{arr}")
print(f"Number of Dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Number of Dimensions = 1
Length --> 12
Shape of an array --> (12,)


In [147]:
for i in arr:
    print(f"Array element --> {i}")

Array element --> 1
Array element --> 2
Array element --> 3
Array element --> 4
Array element --> 5
Array element --> 6
Array element --> 7
Array element --> 8
Array element --> 9
Array element --> 10
Array element --> 11
Array element --> 12


In [149]:
li = [[1,2,3,4,5,6],[7,8,9,10,11,12]]
for i in li:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [150]:
li = [[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[1,2,3,4,5,6],[7,8,9,10,11,12]]]
for i in li:
    for j in i:
        print(j)

[1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12]
[1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12]


In [151]:
li = [[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[1,2,3,4,5,6],[7,8,9,10,11,12]]]
for i in li:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


# 2.np.nditer()

In [152]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [153]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [154]:
arr = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[1,2,3,4,5,6],[7,8,9,10,11,12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [155]:
a = np.nditer(arr)
a

In [156]:
next(a)

array(1)

In [157]:
next(a)

array(2)

In [158]:
next(a)


array(3)

In [159]:
next(a)

array(4)

In [160]:
next(a)

array(5)

In [161]:
next(a)

array(6)

In [162]:
next(a)

array(7)

In [163]:
next(a)


array(8)

In [164]:
next(a)

array(9)

In [165]:
next(a)

array(10)

In [166]:
next(a)

array(11)

In [167]:
next(a)

array(12)

In [168]:
next(a)

array(1)

In [169]:
next(a)

array(2)

In [170]:
next(a)

array(3)

In [171]:
next(a)

array(4)

In [172]:
next(a)

array(5)

In [173]:
next(a)

array(6)

In [174]:
next(a)

array(7)

In [175]:
next(a)

array(8)

In [176]:
next(a)

array(9)

In [177]:
next(a)

array(10)

In [178]:
next(a)

array(11)

In [179]:
next(a)

array(12)

In [180]:
next(a)

StopIteration: 

# 3.np.ndenumerate()

In [181]:
for i,j in enumerate([1,2,3]):
    print(i,j)

0 1
1 2
2 3


In [182]:
arr

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [184]:
for i,j in enumerate(arr):
    print(i,j)

0 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
1 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [185]:
arr

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [186]:
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 0, 5) 6
(0, 1, 0) 7
(0, 1, 1) 8
(0, 1, 2) 9
(0, 1, 3) 10
(0, 1, 4) 11
(0, 1, 5) 12
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 0, 3) 4
(1, 0, 4) 5
(1, 0, 5) 6
(1, 1, 0) 7
(1, 1, 1) 8
(1, 1, 2) 9
(1, 1, 3) 10
(1, 1, 4) 11
(1, 1, 5) 12


# 4.zeros()
- np.zeros(shape,dtype=float)
- Return an array of zeros only
- Weight initialization
- Target Column creation

In [187]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [188]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [189]:
np.zeros(100,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [190]:
import pandas as pd

In [191]:
df = pd.DataFrame(
    {
        "Zeros_Column" : np.zeros(10,int)
    
    }
)
df

Zeros_Column
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0

In [193]:
arr = np.zeros((3,5),int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [195]:
df = pd.DataFrame(arr)
df

0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0

# 5.ones()
- np.ones(shape,dtype=float)
- return an array of ones only

In [198]:
arr = np.ones(10,dtype=float)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [199]:
arr = np.ones(10,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [202]:
df = pd.DataFrame(
    {
        "Zeros_column" : np.zeros(10,int),
        "Ones_column"  : np.ones(10,int)
    }
)
df

Zeros_column  Ones_column
0             0            1
1             0            1
2             0            1
3             0            1
4             0            1
5             0            1
6             0            1
7             0            1
8             0            1
9             0            1

In [203]:
arr = np.zeros((3,5),int)
pd.DataFrame(arr)

0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0