# Numpy Functions

In [1]:
import numpy as np
import pandas as pd

## 1.reshape()


In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [6]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 2.np.nditer()

In [8]:
arr = np.array(
    [[1,2,3],
    [4,5,6]]
)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [11]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [14]:
xyz = np.nditer(arr)
xyz

In [15]:
next(xyz)

array(1)

In [16]:
next(xyz)

array(2)

In [17]:
next(xyz)

array(3)

In [18]:
next(xyz)

array(4)

In [19]:
next(xyz)

array(5)

In [20]:
next(xyz)

array(6)

In [21]:
next(xyz)

StopIteration: 

## 3.np.ndenumerate()

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
for i,j in enumerate(arr):
    print(i,j)

0 [1 2 3]
1 [4 5 6]


In [27]:
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## 4.zeros()

In [29]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [30]:
arr = np.zeros(5,int)
arr

array([0, 0, 0, 0, 0])

In [34]:
arr = np.zeros((5,5),int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## 5.ones()

In [35]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [36]:
arr = np.ones(5,int)
arr

array([1, 1, 1, 1, 1])

In [37]:
arr = np.ones((5,5),int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 6.arange()

In [38]:
range(1,11)

range(1, 11)

In [39]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [46]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [49]:
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [50]:
list(range(5,-1))

[]

In [51]:
arr = np.arange(5,-1)
arr

array([], dtype=int32)

In [54]:
arr = np.arange(5,-1,-1)
arr

array([5, 4, 3, 2, 1, 0])

## 7.linspace()
- Return evenly spaced values
- syntax --> np.linspace(start,end,num=50)

In [56]:
arr = np.linspace(1,50,num=50)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [57]:
arr = np.linspace(1,50,num=25)
arr

array([ 1.        ,  3.04166667,  5.08333333,  7.125     ,  9.16666667,
       11.20833333, 13.25      , 15.29166667, 17.33333333, 19.375     ,
       21.41666667, 23.45833333, 25.5       , 27.54166667, 29.58333333,
       31.625     , 33.66666667, 35.70833333, 37.75      , 39.79166667,
       41.83333333, 43.875     , 45.91666667, 47.95833333, 50.        ])

In [59]:
arr = np.linspace(1,50,num=10)
arr

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [60]:
6.44444444 - 1

5.44444444

In [61]:
11.88888889 - 6.44444444

5.444444450000001

In [66]:
arr = np.linspace(1,50,num=10,retstep=True)
arr

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [67]:
len(arr)

2

In [68]:
arr[0]

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [69]:
arr[1]

5.444444444444445

In [70]:
print(f"The evenly spaced array --> \n\n{arr[0]}\n\nthe step size --> \n\n{arr[1]}")

The evenly spaced array --> 

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]

the step size --> 

5.444444444444445


In [72]:
arr = np.linspace(1,100,num=10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [73]:
23 - 12

11

In [74]:
34 - 23

11

In [75]:
45 - 34

11

In [77]:
arr = np.linspace(1,100,num=10,retstep=True)
arr

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [78]:
arr = np.linspace(1,101,num=10,retstep=True)
arr

(array([  1.        ,  12.11111111,  23.22222222,  34.33333333,
         45.44444444,  56.55555556,  67.66666667,  78.77777778,
         89.88888889, 101.        ]),
 11.11111111111111)

In [79]:
arr = np.linspace(1,50,num=50,retstep=True)
print(f"The evenly spaced array --> \n\n{arr[0]}\n\nThe step size --> \n\n{arr[1]}")

The evenly spaced array --> 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]

The step size --> 

1.0


In [80]:
arr = np.linspace(1,100,num=50,retstep=True)
print(f"The evenly spaced array --> \n\n{arr[0]}\n\nThe step size --> \n\n{arr[1]}")

The evenly spaced array --> 

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]

The step size --> 

2.020408163265306


## 8.eye()
- It will return an array with ones on diagonal and zeros elsewhere
- np.eye(shape,dtype)

In [83]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
arr = np.eye(3,5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [87]:
arr = np.eye(4,5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [88]:
arr = np.eye(4,15,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [89]:
arr = np.eye(10,15,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

## 9.identity()
- Identity matrix will be returned
- num of rows = num of column
- np.identity(value)

In [90]:
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
arr = np.identity(10,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [93]:
arr = np.identity(10,15,dtype=int)
arr

TypeError: identity() got multiple values for argument 'dtype'

## 10.random()
- Used to generate random valued array
- 1.rand()
- 2.randint()
- 3.randn()
- 4.ranf()

### 10.1 rand()
- It will return value between 0 and 1

In [95]:
arr = np.random.rand(5)
arr

array([0.40552408, 0.70997237, 0.23244477, 0.74208353, 0.3486292 ])

In [96]:
arr = np.random.rand(5,5)
arr

array([[0.74250605, 0.99233632, 0.78441429, 0.07129284, 0.41978957],
       [0.1350555 , 0.14570929, 0.34471039, 0.27501159, 0.44064853],
       [0.29384064, 0.5718123 , 0.19913585, 0.85177036, 0.30876057],
       [0.74595875, 0.06390496, 0.04595185, 0.87381255, 0.23760142],
       [0.82204481, 0.26148302, 0.04378899, 0.02446283, 0.40801246]])

In [97]:
pd.DataFrame(arr)

0         1         2         3         4
0  0.742506  0.992336  0.784414  0.071293  0.419790
1  0.135056  0.145709  0.344710  0.275012  0.440649
2  0.293841  0.571812  0.199136  0.851770  0.308761
3  0.745959  0.063905  0.045952  0.873813  0.237601
4  0.822045  0.261483  0.043789  0.024463  0.408012

### 10.2 randint()

In [99]:
arr = np.random.randint(5)
arr

1

In [100]:
arr = np.random.randint(1,5)
arr

1

In [101]:
arr = np.random.randint(1,50)
arr

12

In [102]:
arr = np.random.randint(1,50,size=10)
arr

array([ 8, 18, 24, 47, 18, 40, 28, 14, 30,  5])

In [103]:
arr = np.random.randint(1,50,size=(10,10))
arr

array([[34, 48, 41, 19, 43, 12,  1, 30, 49, 46],
       [ 6, 22, 25, 14,  6, 31, 19,  3,  4, 48],
       [20, 37, 28, 28, 29, 31, 24, 17, 32, 19],
       [37, 39, 48, 37, 39, 20, 20, 49, 40, 25],
       [42, 12, 17, 19, 41, 27, 36, 25, 36, 22],
       [49, 41, 15,  7, 26,  6, 47, 13, 11, 36],
       [49, 46, 27, 19, 17, 22, 48, 49, 39, 26],
       [49, 40, 18, 35, 17, 37, 21, 43,  3, 45],
       [31, 26,  9,  8, 30, 41, 21, 14, 22, 28],
       [34, 41, 28, 40, 46,  4, 40, 44,  9, 22]])

### 10.3 randn()
- It will return values which are normally distributed
- mean 0 and variance 1

In [104]:
arr = np.random.randn(10)
arr

array([-0.09176608, -0.08402765,  0.1035735 , -1.06756583,  1.17953065,
        0.66317048,  1.3640488 , -0.63483939,  1.19673837,  0.07760316])

In [106]:
arr = np.random.randn(10,10)
len(arr)

10

In [107]:
for i in arr:
    print(i)

[ 0.0680703   1.51456013 -0.41722578  2.63609742  1.4045171  -0.93681053
  1.90642741 -0.37853488  0.50149901 -0.71499094]
[ 0.33639019 -0.09741344  1.00548655  0.07855756 -0.49710785 -0.96888419
 -0.45847086  0.57626488 -0.98934397 -0.21083279]
[ 0.98233775  0.53588446 -0.76281739 -0.19751536  1.05937708  0.38757744
 -0.13684036 -0.2060965   0.52387652 -0.40113247]
[-0.3243833  -0.2069141   0.65795783 -1.12317    -0.30019074  0.134578
 -0.09224708  0.15265105 -1.58043689 -0.70969338]
[ 0.26874632 -1.35873455 -0.45079334  1.07595417 -0.49539065  0.22590665
 -1.01968122  1.58861867  1.36479651 -0.92506855]
[ 0.00448398  0.3520507   0.06317972 -0.39522879  0.45067224 -0.72647598
 -0.27609064  0.76012188  0.6433538  -1.4235298 ]
[-0.12709456 -1.07405803 -1.04267355  0.10703802  0.25771641  0.25316624
  2.62632659  0.52516623 -0.67262443 -0.62323442]
[-0.30934379  0.67891168  0.28084185 -1.1277375   0.12951206 -0.18326813
 -0.99781705 -1.8256593   1.31535112  1.93994635]
[ 0.20910326 -1.04

In [108]:
arr

array([[ 0.0680703 ,  1.51456013, -0.41722578,  2.63609742,  1.4045171 ,
        -0.93681053,  1.90642741, -0.37853488,  0.50149901, -0.71499094],
       [ 0.33639019, -0.09741344,  1.00548655,  0.07855756, -0.49710785,
        -0.96888419, -0.45847086,  0.57626488, -0.98934397, -0.21083279],
       [ 0.98233775,  0.53588446, -0.76281739, -0.19751536,  1.05937708,
         0.38757744, -0.13684036, -0.2060965 ,  0.52387652, -0.40113247],
       [-0.3243833 , -0.2069141 ,  0.65795783, -1.12317   , -0.30019074,
         0.134578  , -0.09224708,  0.15265105, -1.58043689, -0.70969338],
       [ 0.26874632, -1.35873455, -0.45079334,  1.07595417, -0.49539065,
         0.22590665, -1.01968122,  1.58861867,  1.36479651, -0.92506855],
       [ 0.00448398,  0.3520507 ,  0.06317972, -0.39522879,  0.45067224,
        -0.72647598, -0.27609064,  0.76012188,  0.6433538 , -1.4235298 ],
       [-0.12709456, -1.07405803, -1.04267355,  0.10703802,  0.25771641,
         0.25316624,  2.62632659,  0.52516623

### 10.4 ranf()
- Return values between 0 and 1


In [110]:
arr = np.random.ranf(10)
arr

array([0.91030992, 0.27830378, 0.0632082 , 0.89067828, 0.93795878,
       0.4974667 , 0.18525554, 0.07211296, 0.86796098, 0.53155926])

In [111]:
arr = np.random.ranf(5)
arr

array([0.12373945, 0.34571832, 0.35015529, 0.38932469, 0.95818167])

In [112]:
dict_np_functions = {
    "Zeros" : np.zeros(10,int),
    "Ones"  : np.ones(10,int),
    "Arange": np.arange(101,111),
    "Linspace" : np.linspace(10,50,num=10),
    "Randint" : np.random.randint(10,50,size=10),
    "Randn" : np.random.randn(10)
}
dict_np_functions

{'Zeros': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'Ones': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'Arange': array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110]),
 'Linspace': array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
        32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ]),
 'Randint': array([43, 41, 24, 31, 46, 14, 36, 43, 37, 28]),
 'Randn': array([ 0.22577536, -0.93676221, -0.3376176 , -2.38887257,  0.82086075,
         0.16927082,  0.91522713,  0.23965248,  1.36037835,  1.65997452])}

In [113]:
pd.DataFrame(dict_np_functions)

Zeros  Ones  Arange   Linspace  Randint     Randn
0      0     1     101  10.000000       43  0.225775
1      0     1     102  14.444444       41 -0.936762
2      0     1     103  18.888889       24 -0.337618
3      0     1     104  23.333333       31 -2.388873
4      0     1     105  27.777778       46  0.820861
5      0     1     106  32.222222       14  0.169271
6      0     1     107  36.666667       36  0.915227
7      0     1     108  41.111111       43  0.239652
8      0     1     109  45.555556       37  1.360378
9      0     1     110  50.000000       28  1.659975

## 11.sort()

In [114]:
arr = np.random.randint(1,10,size=5)
arr

array([4, 2, 6, 8, 6])

In [115]:
np.sort(arr)

array([2, 4, 6, 6, 8])

In [117]:
arr = np.random.randint(1,10,size=15)
arr

array([9, 9, 7, 6, 5, 1, 3, 1, 4, 6, 8, 7, 3, 2, 9])

In [118]:
np.sort(arr)

array([1, 1, 2, 3, 3, 4, 5, 6, 6, 7, 7, 8, 9, 9, 9])

In [119]:
arr = np.random.randint(1,50,size=(3,3))
arr

array([[14, 36, 46],
       [11,  6, 45],
       [37,  6, 10]])

In [121]:
np.sort(arr)

array([[14, 36, 46],
       [ 6, 11, 45],
       [ 6, 10, 37]])

In [123]:
np.sort(arr,axis=1) # Sort Rows

array([[14, 36, 46],
       [ 6, 11, 45],
       [ 6, 10, 37]])

In [125]:
np.sort(arr,axis=0) # Sort column

array([[11,  6, 10],
       [14,  6, 45],
       [37, 36, 46]])

## 12.append()
- syntax :- np.append(array1,array2,axis=None)
   - axis 0 --> Rows
   - axis 1 --> column

In [128]:
li = [1,2,3]
li.append(50)
li

[1, 2, 3, 50]

In [129]:
li.append([1,2,3])

In [130]:
li

[1, 2, 3, 50, [1, 2, 3]]

In [131]:
li.extend([11,22,33])

In [132]:
li

[1, 2, 3, 50, [1, 2, 3], 11, 22, 33]

In [133]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,22,33,44,55])
new_arr = np.append(arr1,arr2)
new_arr

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])

In [134]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array(500)
new_arr = np.append(arr1,arr2)
new_arr

array([  1,   2,   3,   4,   5, 500])

In [135]:
arr1 = np.array([1,2,3,4,5])
# arr2 = np.array(500)
new_arr = np.append(arr1,5000)
new_arr

array([   1,    2,    3,    4,    5, 5000])

In [138]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=0)
new_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [139]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=1)
new_arr

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55]])

In [140]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=1)
new_arr

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55],
       [ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55]])

In [141]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=0)
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [11, 22, 33, 44, 55]])