# Numpy Functions

### 13.np.ceil()
- 3.1 --> 4
- 3.3 --> 4
- 5.9 --> 6
- 9.5 --> 10

In [1]:
import numpy as np

In [2]:
np.ceil(3.5)

4.0

In [3]:
np.ceil(3.9)

4.0

In [4]:
np.ceil(3.1)

4.0

In [5]:
np.ceil(5.9)

6.0

In [6]:
np.ceil(9.0)

9.0

In [8]:
np.ceil(np.array([1,2,3,4,5]))

array([1., 2., 3., 4., 5.])

In [9]:
np.ceil(np.array([1,2,3,4,5.5]))

array([1., 2., 3., 4., 6.])

In [10]:
np.ceil(np.array([1.1,2.2,3.3,4.4,5.5]))

array([2., 3., 4., 5., 6.])

### 14. np.floor()

In [11]:
5/2

2.5

In [12]:
5//2

2

In [13]:
np.floor(2.9)

2.0

In [14]:
np.floor(5.5)

5.0

In [15]:
np.floor(np.array([1,2,3,4,5]))

array([1., 2., 3., 4., 5.])

In [16]:
np.floor(np.array([1,2,3,4,5.5]))

array([1., 2., 3., 4., 5.])

In [17]:
np.floor(np.array([1.1,2.2,3.3,4.4,5.5]))

array([1., 2., 3., 4., 5.])

### 15. np.around()

In [19]:
round(1.7654321,2)

1.77

In [20]:
round(1.764321,2)

1.76

In [21]:
round(1.76,1)

1.8

In [22]:
np.around(np.array([1.7654321,6.7888978,2.4554332,5.667786]),3)

array([1.765, 6.789, 2.455, 5.668])

### 16. np.where()
- np.where(condition)

In [23]:
str1 = "Machine Learning and data science"
ind_li = [ind for ind,val in enumerate(str1.lower()) if val == "a"]
ind_li

[1, 10, 17, 22, 24]

In [24]:
str_array = np.array(list(str1.lower()))
str_array

array(['m', 'a', 'c', 'h', 'i', 'n', 'e', ' ', 'l', 'e', 'a', 'r', 'n',
       'i', 'n', 'g', ' ', 'a', 'n', 'd', ' ', 'd', 'a', 't', 'a', ' ',
       's', 'c', 'i', 'e', 'n', 'c', 'e'], dtype='<U1')

In [25]:
np.where(str_array == "a")

(array([ 1, 10, 17, 22, 24], dtype=int64),)

In [26]:
for i in np.where(str_array == "a"):
    print(i)

[ 1 10 17 22 24]


In [29]:
np.where(str_array == "a")[0]

array([ 1, 10, 17, 22, 24], dtype=int64)

In [30]:
for i in np.where(str_array == "a")[0]:
    print(i)

1
10
17
22
24


In [31]:
list(np.where(str_array == "a")[0])

[1, 10, 17, 22, 24]

In [32]:
np.where(str_array == "a")[0].tolist()

[1, 10, 17, 22, 24]

In [33]:
np.where(np.array([1,2,3,4,5]) != 2)

(array([0, 2, 3, 4], dtype=int64),)

In [34]:
np.where(np.array([1,2,3,4,5]) % 2)

(array([0, 2, 4], dtype=int64),)

In [35]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [36]:
arr[0]

1

In [37]:
arr[1]

2

In [38]:
arr[2]

3

In [39]:
arr[0,2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
np.where(np.array([1,2,3,4,5]) > 2)[0].tolist()

[2, 3, 4]

## Converting array to list

In [41]:
arr = np.array([10,20,30,40,50,60],int)
arr

array([10, 20, 30, 40, 50, 60])

In [42]:
type(arr)

numpy.ndarray

In [43]:
list(arr)

[10, 20, 30, 40, 50, 60]

In [44]:
arr.tolist()

[10, 20, 30, 40, 50, 60]

## Numerical Operations


In [45]:
arr = np.random.randint(10,25,size=5)
arr

array([13, 14, 22, 13, 15])

In [46]:
arr + 5

array([18, 19, 27, 18, 20])

In [47]:
arr - 5

array([ 8,  9, 17,  8, 10])

In [48]:
arr * 2

array([26, 28, 44, 26, 30])

In [49]:
arr / 2

array([ 6.5,  7. , 11. ,  6.5,  7.5])

In [50]:
np.ceil(arr / 2)

array([ 7.,  7., 11.,  7.,  8.])

In [51]:
np.floor(arr / 2)

array([ 6.,  7., 11.,  6.,  7.])

In [52]:
arr // 2

array([ 6,  7, 11,  6,  7], dtype=int32)

In [53]:
arr % 2

array([1, 0, 0, 1, 1], dtype=int32)

In [54]:
arr ** 2

array([169, 196, 484, 169, 225], dtype=int32)

In [56]:
arr ** 3

array([ 2197,  2744, 10648,  2197,  3375], dtype=int32)

## Matrix Addition

In [57]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [58]:
arr2 = np.array([[10,20],[30,40]])
arr2

array([[10, 20],
       [30, 40]])

In [59]:
arr1 + arr2

array([[11, 22],
       [33, 44]])

## np.add()

In [60]:
np.add(arr1,arr2)

array([[11, 22],
       [33, 44]])

## Matrix Multiplication

In [61]:
arr1

array([[1, 2],
       [3, 4]])

In [62]:
arr2

array([[10, 20],
       [30, 40]])

In [63]:
arr1 * arr2

array([[ 10,  40],
       [ 90, 160]])

## np.multiply()

In [64]:
np.multiply(arr1,arr2)

array([[ 10,  40],
       [ 90, 160]])

## Matrix Dot Product

In [65]:
arr1

array([[1, 2],
       [3, 4]])

In [66]:
arr2

array([[10, 20],
       [30, 40]])

In [67]:
np.dot(arr1,arr2)

array([[ 70, 100],
       [150, 220]])