# Numpy-Trigonometry

In [1]:
import numpy as np

In [2]:
pi_val = np.pi

In [3]:
f"The value of pi --> {pi_val}"

'The value of pi --> 3.141592653589793'

In [5]:
sin_30 = np.sin(pi_val / 6) #sin30
sin_30

0.49999999999999994

In [6]:
sin_45 = np.sin(pi_val / 4) #sin45
sin_45

0.7071067811865476

In [7]:
1 / np.sqrt(2)

0.7071067811865475

In [8]:
cos_60 = np.cos(pi_val/3) #cos60
cos_60

0.5000000000000001

# Degree to Redian

In [9]:
np.deg2rad(30)

0.5235987755982988

In [10]:
np.deg2rad(90)

1.5707963267948966

In [12]:
rad_arr = np.deg2rad([0,30,45,60,90])
rad_arr

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [13]:
np.sin(rad_arr)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [14]:
np.cos(rad_arr)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [15]:
np.tan(rad_arr)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

# Radian to Degree

In [16]:
rad_val = np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
degrees = np.rad2deg(rad_val)
degrees

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])