# Numpy-Stats

- 1.mean()
- 2.median()
- 3.mode()
- 4.var()
- 5.std()
- 6.min()
- 7.max()

In [1]:
li = [1,2,3,4,5,6]
sum(li)/ len(li)

3.5

In [2]:
import numpy as np


# 1.mean()

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
len(arr)

10

In [5]:
sum(arr)

55

In [6]:
55 / 10

5.5

In [7]:
np.mean(arr)

5.5

In [8]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
np.mean(arr)

55.0

# 2.median()

In [10]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
(50+60)/2

55.0

In [12]:
np.median(arr)

55.0

In [13]:
arr = np.random.randint(1,10,10)
arr

array([6, 8, 8, 4, 2, 3, 6, 3, 9, 1])

In [15]:
sortedd_arr = np.sort(arr)
sortedd_arr

array([1, 2, 3, 3, 4, 6, 6, 8, 8, 9])

In [16]:
(4+6)/2

5.0

In [17]:
np.median(sortedd_arr)

5.0

In [18]:
arr = np.random.randint(1,10,11)
arr

array([8, 6, 3, 9, 2, 5, 8, 9, 4, 4, 8])

In [20]:
sorted_arr = np.sort(arr)
sorted_arr

array([2, 3, 4, 4, 5, 6, 8, 8, 8, 9, 9])

In [21]:
np.median(sorted_arr)

6.0

# 3.mode()
- Most frequent value of an array

In [22]:
from scipy import stats

In [23]:
arr = np.array([1,1,1,1,1,2,3,4,5,6,7,8,9,10])
stats.mode(arr)

ModeResult(mode=array([1]), count=array([5]))

In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,9,9,9,9,9,10])
stats.mode(arr)

ModeResult(mode=array([9]), count=array([6]))

In [27]:
stats.mode(arr)[0][0]

9

In [28]:
stats.mode(arr)[1][0]

6

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9,9,9,9,9,9,10])
print(f"Array --> {arr}")
Mode = stats.mode(arr)
print(f"The mode of an Array --> {Mode}")
print(f"{Mode[1][0]} Times the {Mode[0][0]} present in an array")

Array --> [ 1  2  3  4  5  6  7  8  9  9  9  9  9  9 10]
The mode of an Array --> ModeResult(mode=array([9]), count=array([6]))
6 Times the 9 present in an array


In [31]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.        ,
       3.        , 3.        , 3.        , 3.        , 3.16227766])

In [32]:
np.cbrt(arr)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.08008382,
       2.08008382, 2.08008382, 2.08008382, 2.08008382, 2.15443469])

In [35]:
np.full(10,1)  # 10 x 1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
np.full(10,23)

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])