# Numpy-Linear Algebra

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[3,2],[4,6]])
print(f"Array 1 --> \n{arr1}")
arr2 = np.array([15,30])
print(f"Array 2 --> \n{arr2}")

Array 1 --> 
[[3 2]
 [4 6]]
Array 2 --> 
[15 30]


In [4]:
res = np.linalg.solve(arr1,arr2)
print(f"Result --> {res}")

Result --> [3. 3.]


In [5]:
arr1 = np.array([[3,5,10],[4,7,13],[2,17,3]])
print(f"Array 1 --> \n{arr1}")
arr2 = np.array([20,30,40])
print(f"Array 2 --> \n{arr2}")

Array 1 --> 
[[ 3  5 10]
 [ 4  7 13]
 [ 2 17  3]]
Array 2 --> 
[20 30 40]


In [7]:
res = np.linalg.solve(arr1,arr2)
print(f"Result --> {res}")

Result --> [ 45.  -1. -11.]


In [8]:
x = 45
y = -1
z = -11

In [9]:
3*45 + 5*(-1) + 10*(-11)

20

In [11]:
3*x + 5*y + 10*z

20

In [12]:
4*x + 7*y + 13*z


30

In [13]:
2*x + 17*y + 3*z

40

# Inverse of Matrix

In [14]:
[
    [1,2],
    [3,4]
]

[[1, 2], [3, 4]]

In [16]:
array1 = np.array([
    [1,2],
    [3,4]
])
array1

array([[1, 2],
       [3, 4]])

In [18]:
np.linalg.inv(array1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Copy of an Array

In [19]:
arr1

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])

In [20]:
arr2 = arr1

In [21]:
arr2

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])

In [23]:
arr2[0][1] = 500

In [24]:
arr1

array([[  3, 500,  10],
       [  4,   7,  13],
       [  2,  17,   3]])

In [25]:
arr2 =arr1.copy()

In [26]:
arr2

array([[  3, 500,  10],
       [  4,   7,  13],
       [  2,  17,   3]])

In [27]:
arr2[0][1] = 5

In [28]:
arr1

array([[  3, 500,  10],
       [  4,   7,  13],
       [  2,  17,   3]])

In [29]:
arr2

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])